localmood-domain/src/main/resources/application-prod.yml

Hotfix: Redis 비밀번호 변경

---

localmood-core/src/main/java/com/localmood/common/s3/service/AwsS3Service.java

Feat: S3 파일 URL 생성 로직 추가 

---

localmood-core/src/main/java/com/localmood/common/exception/ErrorCode.java

Hotfix: 파일 업로드 관련 errorcode 추가 

---

localmood-domain/src/main/java/com/localmood/domain/curation/service/CurationService.java

Feat: 사용자별 큐레이션 목록 조회에 공개 여부 추가

---

localmood-api/src/main/java/com/localmood/api/curation/controller/CurationController.java
localmood-domain/src/main/java/com/localmood/domain/curation/dto/response/CurationDetailResponseDto.java
localmood-domain/src/main/java/com/localmood/domain/curation/service/CurationService.java

Feat: 큐레이션 상세 정보 조회 API에 작성자 식별 추가

---

localmood-api/src/main/java/com/localmood/api/curation/controller/CurationController.java
localmood-domain/src/main/java/com/localmood/domain/curation/service/CurationService.java

Refactor: 큐레이션 API (랜덤 추천, 검색, 키워드 검색, 상세) 미로그인 사용자 접근 허용

---

localmood-api/src/main/java/com/localmood/api/curation/controller/CurationController.java
localmood-domain/src/main/java/com/localmood/domain/curation/service/CurationService.java

Refactor: 큐레이션 검색 (제목, 키워드) API Response 수정

---

localmood-domain/src/main/java/com/localmood/domain/space/entity/SpaceDish.java
localmood-domain/src/main/java/com/localmood/domain/space/entity/SpaceSubType.java

hotifx: add NULL in SpaceDish
hotifx: add NULL in SpaceSubType
Related to: #119
- Resolves #

Hotifx: SpaceDish,SpaceSubType enum NULL 추가

---

localmood-api/src/main/java/com/localmood/api/review/service/ReviewService.java

Fix: 멤버별 공간기록 조회 API NullPointerException 처리 로직 추가

---

localmood-api/src/main/java/com/localmood/api/review/controller/ReviewController.java
localmood-api/src/main/java/com/localmood/api/review/dto/request/ReviewCreateDto.java
localmood-api/src/main/java/com/localmood/api/review/service/ReviewService.java
localmood-core/src/main/java/com/localmood/common/s3/controller/AmazonS3Controller.java

Refactor: 리뷰 생성 API 내 파일 업로드 로직 분리

---

localmood-api/src/main/java/com/localmood/api/review/service/ReviewService.java

Refactor: 공간별 공간기록 조회 API 생성일 포맷팅

---

localmood-api/src/main/java/com/localmood/api/curation/controller/CurationController.java
localmood-domain/src/main/java/com/localmood/domain/curation/service/CurationService.java

Refactor: 큐레이션 생성 API id 응답 반환 추가

---

localmood-core/src/main/java/com/localmood/common/s3/controller/AmazonS3Controller.java

Hotfix: 이미지 업로드 API 요청 형식 수정

---

localmood-core/src/main/java/com/localmood/common/s3/controller/AmazonS3Controller.java

Refactor: 이미지 업로드 API 요청 단일 파일로 수정

---

localmood-core/src/main/java/com/localmood/common/s3/controller/AmazonS3Controller.java

Refactor: 이미지 업로드 uploadFileTemp 추가

---

localmood-core/src/main/java/com/localmood/common/s3/controller/AmazonS3Controller.java

Refactor: uploadFileTemp2 추가

---

localmood-domain/src/main/java/com/localmood/domain/curation/service/CurationService.java
localmood-domain/src/main/java/com/localmood/domain/space/dto/SpaceResponseDto.java

Refactor: 큐레이션 상세조회 API 응답에 공간 ID 추가

---

localmood-core/src/main/java/com/localmood/common/s3/controller/AmazonS3Controller.java
localmood-core/src/main/java/com/localmood/common/s3/dto/ImageRequestDto.java
localmood-core/src/main/java/com/localmood/common/s3/service/AwsS3Service.java

Refactor: uploadFileTemp2 로직 변경

---

localmood-api/src/main/java/com/localmood/api/review/dto/request/ReviewCreateDto.java
localmood-api/src/main/java/com/localmood/api/review/service/ReviewService.java

Refactor: 공간 기록 생성 API에서 이미지 업로드 제거

---

localmood-api/src/main/java/com/localmood/api/curation/controller/CurationController.java
localmood-domain/src/main/java/com/localmood/domain/curation/repository/CurationRepository.java
localmood-domain/src/main/java/com/localmood/domain/curation/service/CurationService.java

Refactor: 큐레이션 조회 API 인기순으로 리뉴얼

---

localmood-api/src/main/java/com/localmood/api/review/dto/response/ReviewDetailResponseDto.java
localmood-api/src/main/java/com/localmood/api/review/service/ReviewService.java
localmood-domain/src/main/java/com/localmood/domain/review/repository/ReviewImgRepository.java

리뷰 조회 관련 API의 이미지 호출 경로 수정
- Resolves #204

Fix: 리뷰 이미지 호출 경로 수정

---

localmood-api/src/main/java/com/localmood/api/space/controller/SpaceScrapController.java
localmood-domain/src/main/java/com/localmood/domain/space/service/SpaceScrapService.java

공간 스크랩 상태 조회 API 신규 생성
- Resolves #210

Feat: 공간 스크랩 상태 조회 API 

---

localmood-domain/src/main/java/com/localmood/domain/space/dto/SpaceDetailDto.java
localmood-domain/src/main/java/com/localmood/domain/space/service/SpaceService.java

공간 상세 화면의 키워드 평가 조회 로직을 업데이트했습니다. 
- Resolves #212

Refactor: 공간 키워드 평가 로직 업데이트

---

localmood-api/src/main/java/com/localmood/api/review/dto/response/ReviewDetailResponseDto.java
localmood-api/src/main/java/com/localmood/api/review/dto/response/ReviewResponseDto.java
localmood-api/src/main/java/com/localmood/api/review/service/ReviewService.java
localmood-domain/src/main/java/com/localmood/domain/curation/dto/response/CurationResponseDto.java
localmood-domain/src/main/java/com/localmood/domain/curation/service/CurationService.java
localmood-domain/src/main/java/com/localmood/domain/space/dto/SpaceResponseDto.java
localmood-domain/src/main/java/com/localmood/domain/space/service/SpaceScrapService.java

스크랩 여부 변수명 통일 작업
- Resolves #214

Refactor: 스크랩 여부 변수명 통일

---

localmood-domain/src/main/java/com/localmood/domain/curation/service/CurationService.java

큐레이션 키워드 응답 형식 배열로 통일
- Resolves #216

Refactor: 큐레이션 키워드 응답 형식 통일 

---

localmood-domain/src/main/java/com/localmood/common/util/ScrapUtil.java

공간 상세조회 API의 스크랩 상태 불러오기 오류 수정
- Resolves #218

Hotfix: 공간 상세조회 API 스크랩 상태 오류 

---

.github/workflows/dev-deploy.yml
.github/workflows/prod-deploy.yml
localmood-api/build.gradle
localmood-api/src/main/java/com/localmood/api/auth/config/WebClientConfig.java
localmood-api/src/main/java/com/localmood/api/auth/controller/AuthController.java
localmood-api/src/main/java/com/localmood/api/auth/controller/KakaoController.java
localmood-api/src/main/java/com/localmood/api/auth/dto/oauth2/KakaoAccount.java
localmood-api/src/main/java/com/localmood/api/auth/dto/oauth2/token/KakaoTokenJsonData.java
localmood-api/src/main/java/com/localmood/api/auth/dto/oauth2/token/KakaoTokenResponse.java
localmood-api/src/main/java/com/localmood/api/auth/dto/oauth2/user/KakaoUserInfoDto.java
localmood-api/src/main/java/com/localmood/api/auth/service/AuthService.java
localmood-api/src/main/resources/templates/loginForm.html
localmood-core/src/main/java/com/localmood/common/config/SwaggerConfig.java
localmood-domain/src/main/java/com/localmood/domain/member/entity/Member.java

카카오 로그인 API 구현
- Resolves #222

Feat: 카카오 로그인 API 

---

localmood-api/src/main/java/com/localmood/api/review/service/ReviewService.java
localmood-domain/src/main/java/com/localmood/common/util/CheckScrapUtil.java
localmood-domain/src/main/java/com/localmood/domain/curation/repository/CurationRepository.java
localmood-domain/src/main/java/com/localmood/domain/curation/service/CurationService.java

Refactor: 공간기록 & 큐레이션 스크랩 여부 로직 변경

---

localmood-domain/src/main/java/com/localmood/domain/space/repository/SpaceRepositoryImpl.java

Refactor: 공간 검색 API 스크랩 여부 로직 변경

---

localmood-domain/src/main/java/com/localmood/domain/space/repository/SpaceRepositoryImpl.java
localmood-domain/src/main/java/com/localmood/domain/space/service/SpaceService.java

공간 조회 (필터, 추천, 상세) API의 스크랩 여부 로직 변경 

Refactor: 공간 조회 (필터, 추천, 상세) API 스크랩 여부 로직 변경 

---

localmood-domain/src/main/java/com/localmood/domain/space/service/SpaceScrapService.java

공간 ID별 스크랩 상태 조회 API의 스크랩 여부 로직 변경

Refactor: 공간 스크랩 상태 조회 API 스크랩 여부 로직 변경

---

localmood-domain/src/main/java/com/localmood/domain/member/dto/MemberScrapCurationDto.java

큐레이션 이미지 응답 필드명 통일
- Resolves #216

Refactor: 큐레이션 이미지 응답 필드명 통일

---

localmood-domain/src/main/java/com/localmood/domain/curation/service/CurationService.java

큐레이션 불필요 import 정리
- Resolves #216

Refactor: 큐레이션 import 정리

---

localmood-api/src/main/java/com/localmood/api/auth/controller/KakaoController.java

Refactor: 카카오 로그인 URI 변경

---

localmood-api/src/main/resources/application.yml

Chore: 설정파일 thymeleaf 추가 

---

localmood-api/src/main/java/com/localmood/api/auth/dto/oauth2/token/KakaoTokenJsonData.java

Refactor: 카카오 토큰 발급 URL generation 수정

---

localmood-api/src/main/java/com/localmood/api/auth/controller/KakaoController.java

Refactor: 카카오 auth import 정리 

---

localmood-api/src/main/java/com/localmood/api/auth/service/AuthService.java

Refactor: auth import 정리 

---

localmood-api/src/main/java/com/localmood/api/auth/controller/KakaoController.java

Feat: 카카오 인가코드 유효성 검사 추가 

---

localmood-api/src/main/java/com/localmood/api/auth/controller/KakaoController.java

Chore: 카카오 로그인 log 추가

---

localmood-api/src/main/java/com/localmood/api/auth/service/AuthService.java

Chore: AuthService 로그 추가

---

localmood-api/src/main/java/com/localmood/api/auth/service/AuthService.java

Refactor: 로그인 AuthenticationException 추가

---

localmood-api/src/main/java/com/localmood/api/auth/service/AuthService.java

Refactor: 카카오 임시 비밀번호로 설정

---

localmood-api/src/main/java/com/localmood/api/auth/service/AuthService.java

Refactor: form 로그인 복원

---

localmood-api/src/main/java/com/localmood/api/auth/controller/KakaoController.java
localmood-api/src/main/java/com/localmood/api/auth/service/AuthService.java

Refactor: 카카오 로그인 메서드 리팩토링

---

localmood-api/src/main/java/com/localmood/api/auth/service/AuthService.java

Refactor: 카카오 로그인 비밀번호 변경

---

localmood-api/src/main/java/com/localmood/api/auth/service/AuthService.java

Refactor: 카카오 회원가입 Transactional 제거

---

localmood-api/src/main/java/com/localmood/api/auth/service/AuthService.java

Refactor: 카카오 회원가입 info log 추가

---

localmood-api/src/main/java/com/localmood/api/auth/controller/KakaoController.java
localmood-api/src/main/java/com/localmood/api/auth/service/AuthService.java

Refactor: 카카오 회원정보 로그 추가

---

localmood-domain/src/main/java/com/localmood/domain/scrap/repository/ScrapSpaceRepositoryImpl.java

멤버별 장소 스크랩 목록 조회 API의 스크랩 여부 로직 변경

Refactor: 멤버별 장소 스크랩 조회 API 스크랩 여부 로직 변경 
